#!/bin/bash
# auto-push.sh — Tạo PR cho mỗi bài TIL mới, chạy tự động bởi macOS LaunchAgent lúc 9:30 AM

REPO="$HOME/VSCProject/Cowork-TIL"
LOG="$REPO/scripts/auto-push.log"

# Đảm bảo PATH đầy đủ (launchd chạy với PATH tối giản)
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG"
}

log "=== auto-push started ==="

cd "$REPO" || { log "ERROR: cannot cd into $REPO"; exit 1; }

# Đảm bảo đang ở main và up-to-date
git checkout main >> "$LOG" 2>&1
git pull >> "$LOG" 2>&1

# Tìm file TIL mới (untracked) trong content/posts/
NEW_POST=$(git ls-files --others --exclude-standard content/posts/ | head -1)

if [ -z "$NEW_POST" ]; then
    log "No new TIL post found. Skipping."
    exit 0
fi

log "New post detected: $NEW_POST"

# Lấy basename để đặt tên branch (vd: 2026-04-29-til-002-sessions-ephemeral-state)
BASENAME=$(basename "$NEW_POST" .md)
BRANCH_NAME="til/${BASENAME}"

log "Creating branch: $BRANCH_NAME"

# Tạo branch mới từ main
git checkout -b "$BRANCH_NAME" >> "$LOG" 2>&1

# Commit post mới + curriculum đã update
git add content/posts/ curriculum.md
git commit -m "til: ${BASENAME}" >> "$LOG" 2>&1

# Push branch lên GitHub
git push origin "$BRANCH_NAME" >> "$LOG" 2>&1

if [ $? -ne 0 ]; then
    log "ERROR: push failed. Check SSH key."
    git checkout main
    exit 1
fi

# Đọc title từ front matter của bài post
POST_TITLE=$(grep '^title:' "$NEW_POST" | sed 's/title: //' | tr -d '"')
if [ -z "$POST_TITLE" ]; then
    POST_TITLE="TIL: ${BASENAME}"
fi

# Tạo PR bằng gh CLI
gh pr create \
    --title "$POST_TITLE" \
    --body "📚 **Daily TIL post** — auto-generated by Cowork agent at 9:05 AM.

Review the post content and merge to publish to the blog.

**Blog URL after merge:** https://DawnHNguuyen.github.io/cowork-til/" \
    --base main \
    --head "$BRANCH_NAME" >> "$LOG" 2>&1

if [ $? -eq 0 ]; then
    log "✅ PR created successfully for: $POST_TITLE"
else
    log "ERROR: gh pr create failed. Is gh CLI authenticated?"
fi

# Quay về main
git checkout main >> "$LOG" 2>&1

log "=== auto-push done ==="
